### ISSUE TITLE
关于旧插件nonebot_plugin_impact的数据迁移

### ISSUE THREAD

**Issue by shi-yingyingjiang** [YuuzukiRin/nonebot_plugin_impart#2]
[nonebot_plugin_impact](https://github.com/Special-Week/nonebot_plugin_impact)已经用了好长时间，能不能把数据迁移过来

**Comment by YuuzukiRin** [comment]
更新版本
找到你的原插件数据库, 通常为\data\impact\impact.db
将impact.db重命名为impart.db
在项目目录下使用 nb localstore 命令来检查数据存储路径Data Dir: \nonebot2
将impart.db放入\nonebot2\nonebot_plugin_impart文件夹中即可

**Comment by YuuzukiRin** [comment]
添加了对原有数据的状态检测适配(如原先length>=25的用户的挑战状态),  请更新插件
