### ISSUE TITLE
排行榜结果显示不正确

### ISSUE THREAD

**Issue by tamakyi** [YuuzukiRin/nonebot_plugin_impart#3]
使用`jj排行榜`功能后，显示的内容仅一名用户且显示获取用户id失败，后台无报错。
```
[message_sent]: {'tim
e': 1730950243, 'self_id': 2863345606, 'post_type': 'message_sent', 'user_id': 2
86334*606, 'message_id': -2147428360, 'real_id': -21474*8360, 'message_seq': -21
4742*360, 'message_type': 'group', 'sender': {'user_id': 2863345*06, 'nickname':
 'Q', 'card': '小 桃 ', 'role': 'admin'}, 'raw_message': '[CQ:at,qq=11*2
14815,name=派 大 ⭐ ][CQ:image,file=b55ef72a-9dd2-4de3-b30a-a310fa4ebf94.png,subTyp
e=0,url=https://gchat.qpic.cn/gchatpic_new/0/0-0-4A73978110940AA77A779DAC2F15D78
B/0,file_size=31236]你 的 排 名 为 6喵 ', 'font': 14, 'sub_type': 'normal', 'message':
 '[CQ:at,qq=11*1214815,name=派 大 ⭐ ][CQ:image,file=b55ef72a-9dd2-4de3-b30a-a310fa
4ebf94.png,subType=0,url=https://gchat.qpic.cn/gchatpic_new/0/0-0-4A73978110940A
A77A779DAC2F15D78B/0,file_size=31236]你 的 排 名 为 6喵 ', 'message_format': 'string',
 'group_id': 7771**254, 'target_id': 7771**254}
```

![Image_37352059995860](https://github.com/user-attachments/assets/75f95108-bd5e-4639-a6bd-deef4a7aa3a2)

**Comment by tamakyi** [comment]
日管理也出问题了```Running Matcher(type='message', module=none
bot_plugin_impart, lineno=70) failed.
Traceback (most recent call last):
  File "/root/momoko/Momoko/bot.py", line 16, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/__in
it__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/driv
ers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/uvicorn/main
.py", line 577, in run
    server.run()
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/uvicorn/serv
er.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/miniconda3/envs/momo/lib/python3.11/asyncio/runners.py", line
190, in run
    return runner.run(main)
  File "/root/miniconda3/envs/momo/lib/python3.11/asyncio/runners.py", line
118, in run
    return self._loop.run_until_complete(task)
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/mess
age.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/mess
age.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/inte
rnal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/inte
rnal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/depe
ndencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
in_impart/handle.py", line 508, in yinpa
    uid, req_user_card, command, prep_list = await self.yinpa_prehandle(
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
in_impart/handle.py", line 373, in yinpa_prehandle
    allow = await plugin_config.fuck_cd_check(event)  # CD检 查 是 否 允 许
  File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
in_impart/config.py", line 105, in fuck_cd_check
    or event.get_user_id() in nonebot.get_driver().config.superusers
NameError: name 'nonebot' is not defined
```

**Comment by YuuzukiRin** [comment]
> 日管理也出问题了```Running Matcher(type='message', module=none bot_plugin_impart, lineno=70) failed. Traceback (most recent call last): File "/root/momoko/Momoko/bot.py", line 16, in nonebot.run(app="**mp_main**:app") File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/**in it**.py", line 335, in run get_driver().run(*args, **kwargs) File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/driv ers/fastapi.py", line 186, in run uvicorn.run( File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/uvicorn/main .py", line 577, in run server.run() File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/uvicorn/serv er.py", line 65, in run return asyncio.run(self.serve(sockets=sockets)) File "/root/miniconda3/envs/momo/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) File "/root/miniconda3/envs/momo/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/mess age.py", line 476, in check_and_run_matcher await _run_matcher(
> 
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/mess
> > age.py", line 428, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/inte
> > rnal/matcher/matcher.py", line 850, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/inte
> > rnal/matcher/matcher.py", line 825, in simple_run
> > await handler(
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot/depe
> > ndencies/**init**.py", line 94, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
> > in_impart/handle.py", line 508, in yinpa
> > uid, req_user_card, command, prep_list = await self.yinpa_prehandle(
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
> > in_impart/handle.py", line 373, in yinpa_prehandle
> > allow = await plugin_config.fuck_cd_check(event)  # CD检 查 是 否 允 许
> > File "/root/miniconda3/envs/momo/lib/python3.11/site-packages/nonebot_plug
> > in_impart/config.py", line 105, in fuck_cd_check
> > or event.get_user_id() in nonebot.get_driver().config.superusers
> > NameError: name 'nonebot' is not defined

可能是原插件的旧方法不适配，更新版本试试

**Comment by YuuzukiRin** [comment]
请更新插件查看是否解决

**Comment by tamakyi** [comment]
> 请更新插件查看是否解决

核实已修复，两个功能都正常显示了。👍
